export const API_VERSIONS_RECEIVE = 'API_VERSIONS_RECEIVE';
export const API_ENDPOINTS_RECEIVE = 'API_ENDPOINTS_RECEIVE';

export const UI_SELECT_VERSION = 'UI_SELECT_VERSION';
export const UI_SELECT_API = 'UI_SELECT_API';

export const REQUEST_SET_METHOD = 'REQUEST_SET_METHOD';
export const REQUEST_SELECT_ENDPOINT = 'REQUEST_SELECT_ENDPOINT';
export const REQUEST_UPDATE_URL = 'REQUEST_UPDATE_URL';
export const REQUEST_UPDATE_PATH_PART_VALUE = 'REQUEST_UPDATE_PATH_PART_VALUE';
export const REQUEST_SET_QUERY_PARAM = 'REQUEST_SET_QUERY_PARAM';
export const REQUEST_SET_BODY_PARAM = 'REQUEST_SET_BODY_PARAM';

export const REQUEST_TRIGGER = 'REQUEST_TRIGGER';
export const REQUEST_RESULTS_RECEIVE = 'REQUEST_RESULTS_RECEIVE';

export const SECURITY_CHECK_FAILED = 'SECURITY_CHECK_FAILED';
export const SECURITY_RECEIVE_USER = 'SECURITY_RECEIVE_USER';
export const SECURITY_LOGOUT = 'SECURITY_LOGOUT';

export const SET_LEFT_DIFF = 'SET_LEFT_DIFF';
export const SET_RIGHT_DIFF = 'SET_RIGHT_DIFF';
